$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        435:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})